Update `devops/Makefile` to support macOS by adding `AWS_VAULT_BACKEND` default and updating references for backend usage.

diff --git a/modules/devops/Makefile b/modules/devops/Makefile
--- a/modules/devops/Makefile
+++ b/modules/devops/Makefile
@@ -3,6 +3,8 @@ AWS_VAULT :=  $(shell which aws-vault)
 SSH_AGENT_FILE := /tmp/bastion_ssh_agent
 ifeq ($(OS),linux)
 AWS_VAULT_BACKEND ?= pass
+else ifeq ($(OS),darwin)
+AWS_VAULT_BACKEND ?= keychain
 endif
 
 .tronador_devops.mk:: Makefile
@@ -45,22 +47,22 @@ devops/aws/bastion/ssm/check:
 	@echo "Retrieving bastion host instance ID from SSM..."
 # Generate temp file to store the instance ID
 	$(eval TEMP_FILE := $(shell mktemp /tmp/bastion_instance_id.XXXXXX))
-	@$(AWS_VAULT) exec $(PROFILE) -- $(AWS) ssm get-parameter --name /cloudopsworks/tronador/bastion/$(SPOKE_NUM)/instance-id --query "Parameter.Value" --region $(REGION) --output text > $(TEMP_FILE)
+	@$(AWS_VAULT) --backend=$(AWS_VAULT_BACKEND) exec $(PROFILE) -- $(AWS) ssm get-parameter --name /cloudopsworks/tronador/bastion/$(SPOKE_NUM)/instance-id --query "Parameter.Value" --region $(REGION) --output text > $(TEMP_FILE)
 	@echo "Bastion host instance ID: $$(cat $(TEMP_FILE))"
 # Check if the instance ID is in running state, if not, start the instance, wait and then proceed
 	@echo "Checking if the bastion host instance is running..."
-	@$(AWS_VAULT) exec $(PROFILE) -- $(AWS) ec2 describe-instance-status --instance-ids $$(cat $(TEMP_FILE)) --region $(REGION) --query "InstanceStatuses[0].InstanceState.Name" --output text | grep -q "running" || \
+	@$(AWS_VAULT) --backend=$(AWS_VAULT_BACKEND) exec $(PROFILE) -- $(AWS) ec2 describe-instance-status --instance-ids $$(cat $(TEMP_FILE)) --region $(REGION) --query "InstanceStatuses[0].InstanceState.Name" --output text | grep -q "running" || \
 		( echo "Bastion host instance is not running, starting it..." && \
-		  $(AWS_VAULT) exec $(PROFILE) -- $(AWS) ec2 start-instances --instance-ids $$(cat $(TEMP_FILE)) --region $(REGION) && \
+		  $(AWS_VAULT) --backend=$(AWS_VAULT_BACKEND) exec $(PROFILE) -- $(AWS) ec2 start-instances --instance-ids $$(cat $(TEMP_FILE)) --region $(REGION) && \
 		  echo "Waiting for the bastion host instance to be running..." && \
-		  $(AWS_VAULT) exec $(PROFILE) -- $(AWS) ec2 wait instance-running --instance-ids $$(cat $(TEMP_FILE)) --region $(REGION) && \
+		  $(AWS_VAULT) --backend=$(AWS_VAULT_BACKEND) exec $(PROFILE) -- $(AWS) ec2 wait instance-running --instance-ids $$(cat $(TEMP_FILE)) --region $(REGION) && \
 		  echo "Bastion host instance is now running." )
 # Before starting the session, ensure that the instance ID is available and ssm agent was able to register with SSM
 	@echo "Checking if the bastion host instance is registered with SSM..."
 # Retry at least 3 times with 20 sec interval to ensure the SSM agent has registered
 # Retry at least 3 times with 20 sec interval to ensure the SSM agent has registered
 	@for i in 1 2 3; do \
-		STATUS=$$($(AWS_VAULT) exec $(PROFILE) -- $(AWS) ssm describe-instance-information --filters "Key=InstanceIds,Values=$$(cat $(TEMP_FILE))" --region $(REGION) --query "InstanceInformationList[0].PingStatus" --output text | grep Online); \
+		STATUS=$$($(AWS_VAULT) --backend=$(AWS_VAULT_BACKEND) exec $(PROFILE) -- $(AWS) ssm describe-instance-information --filters "Key=InstanceIds,Values=$$(cat $(TEMP_FILE))" --region $(REGION) --query "InstanceInformationList[0].PingStatus" --output text | grep Online); \
 		if [ "$$STATUS" = "Online" ]; then \
 			break; \
 		fi; \
@@ -79,7 +81,7 @@ devops/aws/bastion/ssm: devops/aws/load-defaults devops/aws/bastion/ssm/check
 	$(call assert-set,AWS_VAULT)
 # If the instance is registered, start the SSM session
 	@echo "Starting SSM session to the bastion host..."
-	@$(AWS_VAULT) exec $(PROFILE) -- $(AWS) ssm start-session --target $$(cat $(TEMP_FILE)) --region $(REGION)
+	@$(AWS_VAULT) --backend=$(AWS_VAULT_BACKEND) exec $(PROFILE) -- $(AWS) ssm start-session --target $$(cat $(TEMP_FILE)) --region $(REGION)
 # Clean up the temporary file
 	@rm -f $(TEMP_FILE)
 
@@ -93,7 +95,7 @@ devops/aws/bastion/ssm-port-forward/%: devops/aws/load-defaults devops/aws/basti
 	$(eval SRC_PORT := $(word 1,$(SRC_DEST)))
 	$(eval DEST_PORT := $(word 2,$(SRC_DEST)))
 	@echo "Starting SSM port forwarding session to the bastion host... from: $(SRC_PORT) to: $(DEST_PORT)"
-	@$(AWS_VAULT) exec $(PROFILE) -- $(AWS) ssm start-session --target $$(cat $(TEMP_FILE)) --document-name AWS-StartPortForwardingSession --parameters '{"portNumber":["$(DEST_PORT)"],"localPortNumber":["$(SRC_PORT)"]}' --region $(REGION) || echo "... Command failed or interrupted, exiting."
+	@$(AWS_VAULT) --backend=$(AWS_VAULT_BACKEND) exec $(PROFILE) -- $(AWS) ssm start-session --target $$(cat $(TEMP_FILE)) --document-name AWS-StartPortForwardingSession --parameters '{"portNumber":["$(DEST_PORT)"],"localPortNumber":["$(SRC_PORT)"]}' --region $(REGION) || echo "... Command failed or interrupted, exiting."
 # Clean up the temporary file
 	@rm -f $(TEMP_FILE)
 
@@ -103,11 +105,11 @@ devops/aws/bastion/ssh-port-forward/%: devops/aws/load-defaults devops/aws/basti
 	$(call assert-set,AWS_VAULT)
 # Retrieve instance's public IP address from EC2 instance metadata instance id is defiende in $(TEMP_FILE)
 	@echo "Retrieving bastion host public IP address..."
-	$(eval BASTION_IP := $(shell $(AWS_VAULT) exec $(PROFILE) -- $(AWS) ec2 describe-instances --instance-ids $$(cat $(TEMP_FILE)) --region $(REGION) --query "Reservations[0].Instances[0].PublicIpAddress" --output text))
+	$(eval BASTION_IP := $(shell $(AWS_VAULT) --backend=$(AWS_VAULT_BACKEND) exec $(PROFILE) -- $(AWS) ec2 describe-instances --instance-ids $$(cat $(TEMP_FILE)) --region $(REGION) --query "Reservations[0].Instances[0].PublicIpAddress" --output text))
 	@echo "Bastion host public IP address: $(BASTION_IP)"
 # Retrieve the key name from ssm parameter store
 	@echo "Retrieving bastion host key name from SSM..."
-	$(eval KEY_NAME := $(shell $(AWS_VAULT) exec $(PROFILE) -- $(AWS) ssm get-parameter --name /cloudopsworks/tronador/bastion/$(SPOKE_NUM)/key-secret-name --query "Parameter.Value" --region $(REGION) --output text))
+	$(eval KEY_NAME := $(shell $(AWS_VAULT) --backend=$(AWS_VAULT_BACKEND) exec $(PROFILE) -- $(AWS) ssm get-parameter --name /cloudopsworks/tronador/bastion/$(SPOKE_NUM)/key-secret-name --query "Parameter.Value" --region $(REGION) --output text))
 # Start SSH agent to manage keys and validate is not already running
 	@echo "Starting SSH agent..."
 	@if [ ! -f $(SSH_AGENT_FILE) ]; then \
@@ -123,7 +125,7 @@ devops/aws/bastion/ssh-port-forward/%: devops/aws/load-defaults devops/aws/basti
 	$(eval DEST_PORT := $(word 3,$(SRC_DEST)))
 # Retrieve from ssm parameter the instance-user value
 	@echo "Retrieving bastion host instance user from SSM..."
-	$(eval INSTANCE_USER := $(shell $(AWS_VAULT) exec $(PROFILE) -- $(AWS) ssm get-parameter --name /cloudopsworks/tronador/bastion/$(SPOKE_NUM)/instance-user --query "Parameter.Value" --region $(REGION) --output text ))
+	$(eval INSTANCE_USER := $(shell $(AWS_VAULT) --backend=$(AWS_VAULT_BACKEND) exec $(PROFILE) -- $(AWS) ssm get-parameter --name /cloudopsworks/tronador/bastion/$(SPOKE_NUM)/instance-user --query "Parameter.Value" --region $(REGION) --output text ))
 	@bash -c "trap 'trap - SIGINT SIGTERM ERR; eval \`cat $(SSH_AGENT_FILE)\`; ssh-agent -k ; rm -f $(SSH_AGENT_FILE); rm -f $(TEMP_FILE); exit 1' SIGINT SIGTERM ERR; SSH_AGENT_FILE=$(SSH_AGENT_FILE) SRC_PORT=$(SRC_PORT) DEST_ADDR=$(DEST_ADDR) DEST_PORT=$(DEST_PORT) INSTANCE_USER=$(INSTANCE_USER) BASTION_IP=$(BASTION_IP) $(MAKE) devops/aws/bastion/ssh-run"
 # Clean up the temporary file
 	@rm -f $(TEMP_FILE)
@@ -132,7 +134,7 @@ devops/aws/bastion/ssh-keyadd:
 # Retrieve the contents of SecretsManager secret named by  $(KEYNAME)
 	@echo "Retrieving bastion host key contents from SecretsManager..."
 	@eval `cat $(SSH_AGENT_FILE)` ; \
- 		$(AWS_VAULT) exec $(PROFILE) -- $(AWS) secretsmanager get-secret-value --secret-id $(KEY_NAME) --query "SecretString" --region $(REGION) --output text | ssh-add -
+ 		$(AWS_VAULT) --backend=$(AWS_VAULT_BACKEND) exec $(PROFILE) -- $(AWS) secretsmanager get-secret-value --secret-id $(KEY_NAME) --query "SecretString" --region $(REGION) --output text | ssh-add -
 
 devops/aws/bastion/ssh-run:
 	@echo "Starting SSH port forwarding session to the bastion host... from: $(SRC_PORT) address-to: $(DEST_ADDR) to: $(DEST_PORT)"
@@ -151,15 +153,15 @@ devops/aws/bastion/shutdown: devops/aws/load-defaults
 	$(call assert-set,AWS)
 	$(call assert-set,AWS_VAULT)
 	$(eval TEMP_FILE := $(shell mktemp /tmp/bastion_instance_id.XXXXXX))
-	@$(AWS_VAULT) exec $(PROFILE) -- $(AWS) ssm get-parameter --name /cloudopsworks/tronador/bastion/$(SPOKE_NUM)/instance-id --query "Parameter.Value" --region $(REGION) --output text > $(TEMP_FILE)
+	@$(AWS_VAULT) --backend=$(AWS_VAULT_BACKEND) exec $(PROFILE) -- $(AWS) ssm get-parameter --name /cloudopsworks/tronador/bastion/$(SPOKE_NUM)/instance-id --query "Parameter.Value" --region $(REGION) --output text > $(TEMP_FILE)
 	@echo "Bastion host instance ID: $$(cat $(TEMP_FILE))"
 # Check if the instance ID is in running state, if not, start the instance, wait and then proceed
 	@echo "Checking if the bastion host instance is running..."
-	@$(AWS_VAULT) exec $(PROFILE) -- $(AWS) ec2 describe-instance-status --instance-ids $$(cat $(TEMP_FILE)) --region $(REGION) --query "InstanceStatuses[0].InstanceState.Name" --output text | grep -q "None" || \
+	@$(AWS_VAULT) --backend=$(AWS_VAULT_BACKEND) exec $(PROFILE) -- $(AWS) ec2 describe-instance-status --instance-ids $$(cat $(TEMP_FILE)) --region $(REGION) --query "InstanceStatuses[0].InstanceState.Name" --output text | grep -q "None" || \
 		( echo "Bastion host instance is running, stopping it..." && \
-		  $(AWS_VAULT) exec $(PROFILE) -- $(AWS) ec2 stop-instances --instance-ids $$(cat $(TEMP_FILE)) --region $(REGION) && \
+		  $(AWS_VAULT) --backend=$(AWS_VAULT_BACKEND) exec $(PROFILE) -- $(AWS) ec2 stop-instances --instance-ids $$(cat $(TEMP_FILE)) --region $(REGION) && \
 		  echo "Waiting for the bastion host instance to be totally stopped..." && \
-		  $(AWS_VAULT) exec $(PROFILE) -- $(AWS) ec2 wait instance-stopped --instance-ids $$(cat $(TEMP_FILE)) --region $(REGION) && \
+		  $(AWS_VAULT) --backend=$(AWS_VAULT_BACKEND) exec $(PROFILE) -- $(AWS) ec2 wait instance-stopped --instance-ids $$(cat $(TEMP_FILE)) --region $(REGION) && \
 		  echo "Bastion host instance is now stopped." )
 # Clean up the temporary file
 	@rm -f $(TEMP_FILE)
